[package]
name = "CounterV2"
version = "0.0.1"

[addresses]
counter_addr = "{{ADDR}}"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
