[package]
name = "TestV1"
version = "1.0.0"

[addresses]
test_addr = "0x123"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
